//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JassTournamentManager.App.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JassTournamentManager.App.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jass Tournament Manager.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melde dich an oder erstelle dein Konto..
        /// </summary>
        public static string Auth_Subtitle {
            get {
                return ResourceManager.GetString("Auth_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereits ein Konto? → Anmelden.
        /// </summary>
        public static string Auth_SwitchToLogin {
            get {
                return ResourceManager.GetString("Auth_SwitchToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch kein Konto? → Registrieren.
        /// </summary>
        public static string Auth_SwitchToRegister {
            get {
                return ResourceManager.GetString("Auth_SwitchToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail *.
        /// </summary>
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort *.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Register_BackButton {
            get {
                return ResourceManager.GetString("Register_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler übernehmen.
        /// </summary>
        public static string Register_ClaimUser {
            get {
                return ResourceManager.GetString("Register_ClaimUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string Register_ClaimUserNoButton {
            get {
                return ResourceManager.GetString("Register_ClaimUserNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist du bereits auf einer ewigen Rangliste erfasst?.
        /// </summary>
        public static string Register_ClaimUserQuestion {
            get {
                return ResourceManager.GetString("Register_ClaimUserQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falls ja, existiert bereits ein Spielerprofil für dich..
        /// </summary>
        public static string Register_ClaimUserQuestionAddOn {
            get {
                return ResourceManager.GetString("Register_ClaimUserQuestionAddOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Register_ClaimUserYesButton {
            get {
                return ResourceManager.GetString("Register_ClaimUserYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort bestätigen *.
        /// </summary>
        public static string Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Register_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto erstellen.
        /// </summary>
        public static string Register_CreateAccount {
            get {
                return ResourceManager.GetString("Register_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail *.
        /// </summary>
        public static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte bestätige dein Passwort, indem du es wiederholst..
        /// </summary>
        public static string Register_ErrorMessage_ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse darf höchstens 320 Zeichen lang sein..
        /// </summary>
        public static string Register_ErrorMessage_EmailMaxLength {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib eine gültige E-Mail-Adresse ein..
        /// </summary>
        public static string Register_ErrorMessage_EmailNotValid {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib deine E-Mail-Adresse ein..
        /// </summary>
        public static string Register_ErrorMessage_EmailRequired {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorname darf höchstens 50 Zeichen lang sein..
        /// </summary>
        public static string Register_ErrorMessage_FirstNameMaxLength {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_FirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib deinen Vornamen ein..
        /// </summary>
        public static string Register_ErrorMessage_FirstNameRequired {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Nachname darf höchstens 50 Zeichen lang sein..
        /// </summary>
        public static string Register_ErrorMessage_LastNameMaxLength {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_LastNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib deinen Nachnamen ein..
        /// </summary>
        public static string Register_ErrorMessage_LastNameRequired {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwende mindestens 8 Zeichen, eine Zahl und ein Sonderzeichen..
        /// </summary>
        public static string Register_ErrorMessage_PasswordMinRequirements {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_PasswordMinRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Passwörter stimmen nicht überein..
        /// </summary>
        public static string Register_ErrorMessage_PasswordMismatch {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib dein Passwort ein..
        /// </summary>
        public static string Register_ErrorMessage_PasswordRequired {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte prüfe deine obigen Angaben..
        /// </summary>
        public static string Register_ErrorMessage_RegisterFormInvalid {
            get {
                return ResourceManager.GetString("Register_ErrorMessage_RegisterFormInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname *.
        /// </summary>
        public static string Register_FirstName {
            get {
                return ResourceManager.GetString("Register_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname *.
        /// </summary>
        public static string Register_LastName {
            get {
                return ResourceManager.GetString("Register_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string Register_NextButton {
            get {
                return ResourceManager.GetString("Register_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Spieler gefunden..
        /// </summary>
        public static string Register_NoClaimableUsersFound {
            get {
                return ResourceManager.GetString("Register_NoClaimableUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort *.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler suchen.
        /// </summary>
        public static string Register_SearchPlayer {
            get {
                return ResourceManager.GetString("Register_SearchPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
    }
}
