// <auto-generated />
using System;
using JassTournamentManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JassTournamentManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JtmDbContext))]
    [Migration("20260526000959_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("jtm")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GameNumber")
                        .HasColumnType("integer")
                        .HasColumnName("game_number");

                    b.Property<bool>("MatchBonusEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("match_bonus_enabled");

                    b.Property<Guid>("PairingId")
                        .HasColumnType("uuid")
                        .HasColumnName("pairing_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PairingId")
                        .HasDatabaseName("idx_game_pairing");

                    b.HasIndex("PairingId", "GameNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_games_pairing_game_number");

                    b.ToTable("games", "jtm");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.JassTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("idx_table_organizer");

                    b.HasIndex("OrganizerId", "IsActive")
                        .HasDatabaseName("idx_table_active");

                    b.ToTable("jass_tables", "jtm");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.Pairing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GamesPerRound")
                        .HasColumnType("integer")
                        .HasColumnName("games_per_round");

                    b.Property<Guid>("JassTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("jass_table_id");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JassTableId");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("idx_pairing_round");

                    b.HasIndex("RoundId", "JassTableId")
                        .IsUnique()
                        .HasDatabaseName("ux_pairings_round_jass_table");

                    b.ToTable("pairings", "jtm");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.PairingParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnteredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("entered_by");

                    b.Property<Guid>("PairingId")
                        .HasColumnType("uuid")
                        .HasColumnName("pairing_id");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("team");

                    b.Property<Guid>("TournamentParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_participant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EnteredBy");

                    b.HasIndex("PairingId")
                        .HasDatabaseName("idx_pairing_participant_pairing");

                    b.HasIndex("TournamentParticipantId")
                        .HasDatabaseName("idx_pairing_participant_participant");

                    b.HasIndex("PairingId", "TournamentParticipantId")
                        .IsUnique()
                        .HasDatabaseName("ux_pairing_participants_pairing_tournament_participant");

                    b.ToTable("pairing_participants", "jtm");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("idx_round_tournament");

                    b.HasIndex("TournamentId", "RoundNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_rounds_tournament_round_number");

                    b.ToTable("rounds", "jtm");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("idx_tournament_organizer");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_tournament_status");

                    b.ToTable("tournaments", "jtm");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.TournamentParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPlaying")
                        .HasColumnType("boolean")
                        .HasColumnName("is_playing");

                    b.Property<string>("RegistrationMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("registration_method");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("idx_participant_tournament");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_participant_user");

                    b.HasIndex("UserId", "TournamentId")
                        .IsUnique()
                        .HasDatabaseName("ux_tournament_participants_user_tournament");

                    b.ToTable("tournament_participants", "jtm");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.TournamentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId")
                        .IsUnique()
                        .HasDatabaseName("idx_tournament_template_organizer");

                    b.ToTable("tournament_templates", "jtm");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSysAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sys_admin");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("MergeTargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("merge_target_user_id");

                    b.Property<DateTimeOffset?>("MergedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("merged_at");

                    b.Property<Guid?>("MergedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_by");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Email"), true);

                    b.HasIndex("MergeTargetUserId")
                        .HasDatabaseName("idx_users_merge_target_user_id");

                    b.HasIndex("MergedBy");

                    b.ToTable("users", "jtm");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.Game", b =>
                {
                    b.HasOne("JassTournamentManager.Domain.Entities.Pairing", null)
                        .WithMany("Games")
                        .HasForeignKey("PairingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JassTournamentManager.Domain.ValueObjects.GameScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("EnteredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("entered_at");

                            b1.Property<Guid>("EnteredBy")
                                .HasColumnType("uuid")
                                .HasColumnName("entered_by");

                            b1.Property<bool>("TeamAMatchBonusAchieved")
                                .HasColumnType("boolean")
                                .HasColumnName("team_a_match_bonus_achieved");

                            b1.Property<int>("TeamAPoints")
                                .HasColumnType("integer")
                                .HasColumnName("team_a_points");

                            b1.Property<bool>("TeamBMatchBonusAchieved")
                                .HasColumnType("boolean")
                                .HasColumnName("team_b_match_bonus_achieved");

                            b1.Property<int>("TeamBPoints")
                                .HasColumnType("integer")
                                .HasColumnName("team_b_points");

                            b1.HasKey("GameId");

                            b1.HasIndex("EnteredBy");

                            b1.ToTable("games", "jtm");

                            b1.HasOne("JassTournamentManager.Domain.Entities.TournamentParticipant", null)
                                .WithMany()
                                .HasForeignKey("EnteredBy")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("Score");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.JassTable", b =>
                {
                    b.HasOne("JassTournamentManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.Pairing", b =>
                {
                    b.HasOne("JassTournamentManager.Domain.Entities.JassTable", null)
                        .WithMany()
                        .HasForeignKey("JassTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JassTournamentManager.Domain.Entities.Round", null)
                        .WithMany("Pairings")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.PairingParticipant", b =>
                {
                    b.HasOne("JassTournamentManager.Domain.Entities.TournamentParticipant", null)
                        .WithMany()
                        .HasForeignKey("EnteredBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JassTournamentManager.Domain.Entities.Pairing", null)
                        .WithMany("Participants")
                        .HasForeignKey("PairingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JassTournamentManager.Domain.Entities.TournamentParticipant", null)
                        .WithMany()
                        .HasForeignKey("TournamentParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.Round", b =>
                {
                    b.HasOne("JassTournamentManager.Domain.Entities.Tournament", null)
                        .WithMany("Rounds")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("JassTournamentManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("JassTournamentManager.Domain.ValueObjects.TournamentConfigValues", "ConfigValues", b1 =>
                        {
                            b1.Property<Guid>("TournamentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("GamesPerRound")
                                .HasColumnType("integer")
                                .HasColumnName("games_per_round");

                            b1.Property<bool>("IsFixedTeams")
                                .HasColumnType("boolean")
                                .HasColumnName("is_fixed_teams");

                            b1.Property<bool>("MatchBonusEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("match_bonus_enabled");

                            b1.Property<int>("NumberOfRounds")
                                .HasColumnType("integer")
                                .HasColumnName("number_of_rounds");

                            b1.Property<string>("ScoreVisibility")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("score_visibility");

                            b1.HasKey("TournamentId");

                            b1.ToTable("tournaments", "jtm");

                            b1.WithOwner()
                                .HasForeignKey("TournamentId");
                        });

                    b.OwnsOne("JassTournamentManager.Domain.ValueObjects.TournamentDetails", "Details", b1 =>
                        {
                            b1.Property<Guid>("TournamentId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<string>("Location")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("location");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<string>("TournamentCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("tournament_code");

                            b1.HasKey("TournamentId");

                            b1.HasIndex("TournamentCode")
                                .IsUnique()
                                .HasDatabaseName("ux_tournaments_tournament_code");

                            b1.ToTable("tournaments", "jtm");

                            b1.WithOwner()
                                .HasForeignKey("TournamentId");
                        });

                    b.Navigation("ConfigValues")
                        .IsRequired();

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.TournamentParticipant", b =>
                {
                    b.HasOne("JassTournamentManager.Domain.Entities.Tournament", null)
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JassTournamentManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.TournamentTemplate", b =>
                {
                    b.HasOne("JassTournamentManager.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("JassTournamentManager.Domain.Entities.TournamentTemplate", "OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JassTournamentManager.Domain.ValueObjects.TournamentConfigValues", "ConfigValues", b1 =>
                        {
                            b1.Property<Guid>("TournamentTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("GamesPerRound")
                                .HasColumnType("integer")
                                .HasColumnName("games_per_round");

                            b1.Property<bool>("IsFixedTeams")
                                .HasColumnType("boolean")
                                .HasColumnName("is_fixed_teams");

                            b1.Property<bool>("MatchBonusEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("match_bonus_enabled");

                            b1.Property<int>("NumberOfRounds")
                                .HasColumnType("integer")
                                .HasColumnName("number_of_rounds");

                            b1.Property<string>("ScoreVisibility")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("score_visibility");

                            b1.HasKey("TournamentTemplateId");

                            b1.ToTable("tournament_templates", "jtm");

                            b1.WithOwner()
                                .HasForeignKey("TournamentTemplateId");
                        });

                    b.Navigation("ConfigValues")
                        .IsRequired();
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.User", b =>
                {
                    b.HasOne("JassTournamentManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MergeTargetUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JassTournamentManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MergedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.Pairing", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.Round", b =>
                {
                    b.Navigation("Pairings");
                });

            modelBuilder.Entity("JassTournamentManager.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
